### PR TITLE
Prevent race-condition of two requests on same action with different route params

### PR DESCRIPTION
**Pull request by XCame**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

I ran in this issue today because of a smart user who thought: 

> If I need to fill in the same information for different entities, I just open up each edit page in a 
> single tab, fill in the dates and then save, switch tab, save, switch tab, save, switch tab [...]

Due to lag it lead to the first POST request being sent, saved in session via the key 'prg_post1', then the second POST request came in, the prg-plugin found an existing container for 'prg_post1' although it was saved from the first request and processed it. 

This wouldn't be an issue it the identifier of the entity that this data should be processed for wasn't identified by a parameter in the route. 

To reproduce: 
1. create an action that produces a form, that gets handled via prg
2. call that action via a route containing a route-parameter e.g. /myAction/:id
3. check for route parameter and delay execution of redirect if param == A to simulate lag
4. Send form from action called with param = A, while request(A) is delayed, send form from action called with param = B

Expected:
Form from /myAction/A contains data sent from /myAction/A
Form from /myAction/B contains data sent from /myAction/B

Actual result:
Form from /myAction/B contains data sent from /myAction/A

### CODE REVIEW

**Comment by Xerkus** [comment]
Please rebase onto master.

I think this highlights two issues. Second is the wrong PRG usage. That wrong usage is suggested by the docs.
Correct flow should be:

- GET: present form
- POST: validate form
  - Valid form: process and redirect (GET or elsewhere)
  - Invalid form: use PRG to save the post data
- GET: obtain PRG data to present form. Run validation to present validation errors

**Comment by XCame** [comment]
I'm really sorry, but it looks like your "please rebase onto master" exceeds my git skills.


And out of curiosity: What is the first issue? If the second is the wrong prg usage?
But I agree. Your suggested flow makes much more sense than the usage describe in the examples.

**Comment by XCame** [comment]
Okay, I cherry-picked my commit to my fork of master. 
But I need to close this PR and open another one to compare against master, don't I?

**Comment by weierophinney** [comment]
> But I need to close this PR and open another one to compare against master, don't I?

No - you can force push to the same branch (`git push -f {remote} {local branch}:{remote branch}`), and the PR will pick up the changes. Then edit the PR to change the target branch here.

**Comment by Xerkus** [comment]
> I'm really sorry, but it looks like your "please rebase onto master" exceeds my git skills.

@XCame join our chat and we will be happy to guide you! https://laminas.dev/chat/

**Comment by XCame** [comment]
Opened PR again from correct branch. #2

**Pull request closed without merging**
